#!/usr/bin/env bash

# Script to create the 'item_images' Supabase Storage bucket.

# Exit immediately if a command exits with a non-zero status.
set -e

BUCKET_NAME="item_images"

echo "Attempting to create Supabase Storage bucket: $BUCKET_NAME (public)"

# Basic check for Supabase CLI
if ! command -v supabase &> /dev/null
then
    echo "Error: Supabase CLI could not be found. Please install it first."
    echo "See: https://supabase.com/docs/guides/cli"
    exit 1
fi


# Inform the user about prerequisites
echo "Please ensure you are logged in (supabase login) and linked to your project (supabase link)."

# Create the bucket using the Supabase CLI
if supabase storage buckets create "$BUCKET_NAME" --public; then
  echo "Successfully created public bucket: '$BUCKET_NAME'"
  echo ""
  echo "IMPORTANT: Review and configure Bucket Policies in your Supabase Dashboard."
  echo "For public URLs generated by getPublicUrl to work, you typically need a policy allowing SELECT (read) operations for the 'anon' role."
else
  echo "Error creating bucket '$BUCKET_NAME'. It might already exist, or there was another issue."
  exit 1
fi

exit 0 