import { Injectable, inject, signal } from '@angular/core';
import { SupabaseService } from './supabase.service';
import { PostgrestSingleResponse, PostgrestError, PostgrestMaybeSingleResponse } from '@supabase/supabase-js';
// Import the interface from the dedicated file
import { AccountInformation } from '../interfaces/account-information.interfaces';
// Import the new Loan interface
import { Loan } from '../interfaces/loan.interfaces';

// Remove the interface definition from here
/*
export interface AccountInformation {
  id?: number; // Assuming an auto-incrementing ID primary key
  name_of_borrower: string;
  provider_subject_no: string | null;
  gender: string | null;
  civil_status: string | null;
  type_of_id: string | null;
  birthday_borrower: string | null; // Consider using Date type if appropriate
  age: number | null;
  mothers_maiden_name_borrower: string | null;
  name_of_co_borrower_maker: string | null;
  security_collateral: string | null;
  mode_of_payment: string | null;
  store_name: string | null;
  residence_address: string | null;
  length_of_stay_in_residence: string | null; // Consider number type?
  store_address: string | null;
  area: string | null;
  contact_no_borrower: string | null;
  classification: string | null;
  store_category: string | null;
  account_relationship_officer: string | null;
  retail_partner: string | null;
  created_at?: string; // Assuming Supabase adds this automatically
  // Add any other relevant columns from your table
}
*/

@Injectable({
  providedIn: 'root'
})
export class BorrowerService {
  private supabaseService = inject(SupabaseService);
  // Define the table name as a constant for easy modification
  private tableName = 'account_information';

  // Add isLoading signal
  isLoading = signal<boolean>(false);

  // Helper to get the Supabase client
  private get supabase() {
    return this.supabaseService.supabase;
  }

  constructor() { }

  /**
   * Fetches all records from the account_information table, ordered by creation date descending.
   * @returns Promise resolving to the Supabase response containing an array of AccountInformation or an error.
   */
  async getAllBorrowers(): Promise<PostgrestSingleResponse<AccountInformation[]>> {
    try {
      const response = await this.supabase
        .from(this.tableName)
        .select('*')
        .order('created_at', { ascending: false }); // Order by newly created
      
      console.log('getAllBorrowers response:', response);
      return response;
    } catch (error: any) { 
       console.error('Unexpected error in getAllBorrowers:', error);
       const pgError: PostgrestError = { message: error?.message || 'Client Error', details: '', hint: '', code: 'CLIENT_ERR', name: 'ClientGetAllError' };
       return { data: null, error: pgError, status: 0, statusText: 'Client Error', count: null };
    }
  }

  /**
   * Fetches a single borrower record by its ID.
   * @param id The ID of the borrower to fetch.
   * @returns Promise resolving to the Supabase response containing the borrower or an error.
   */
  async getBorrowerById(id: number): Promise<PostgrestMaybeSingleResponse<AccountInformation>> {
      try {
          const response = await this.supabase
              .from(this.tableName)
              .select('*')
              .eq('id', id)
              .maybeSingle(); // Use maybeSingle to handle potential null result without error
          
          console.log('getBorrowerById response:', response);
          return response;
      } catch (error: any) {
         console.error('Unexpected error in getBorrowerById:', error);
         const pgError: PostgrestError = { message: error?.message || 'Client Fetch Error', details: '', hint: '', code: 'CLIENT_FETCH_ERR', name: 'ClientFetchError' };
         return { data: null, error: pgError, status: 0, statusText: 'Client Fetch Error', count: null };
      }
  }

  /**
   * Adds a new borrower record to the account_information table.
   * @param borrowerData The data for the new borrower (should match AccountInformation, excluding id/created_at)
   * @returns Promise resolving to the Supabase response containing the newly created record or an error.
   */
  async addBorrower(borrowerData: Partial<AccountInformation>): Promise<PostgrestSingleResponse<AccountInformation>> {
    try {
        // Remove id and created_at if they somehow exist in the input object
        // as these are usually auto-generated by the database.
        const { id, created_at, ...insertData } = borrowerData;

        const response = await this.supabase
            .from(this.tableName)
            .insert(insertData as AccountInformation) // Cast might be needed depending on strictness
            .select() // Select the newly inserted row
            .single(); // Expecting a single row back

        return response;
    } catch (error: any) {
        console.error('Unexpected error in addBorrower:', error);
        const pgError: PostgrestError = {
            message: error?.message || 'An unexpected client-side error occurred during insert.',
            details: error?.details || 'No additional details available.',
            hint: error?.hint || '',
            code: error?.code || 'CLIENT_INSERT_ERROR',
            name: 'ClientSideInsertError'
        };
        return {
            data: null,
            error: pgError,
            status: 0,
            statusText: 'Client Insert Error',
            count: null
        };
    }
  }

  /**
   * Updates an existing borrower record.
   * @param id The ID of the borrower to update.
   * @param borrowerData The updated data.
   * @returns Promise resolving to the Supabase response.
   */
  async updateBorrower(id: number, borrowerData: Partial<AccountInformation>): Promise<PostgrestSingleResponse<AccountInformation>> {
     try {
         // Remove id and created_at if they somehow exist in the update object
         const { id: dataId, created_at, ...updateData } = borrowerData;

         const response = await this.supabase
             .from(this.tableName)
             .update(updateData)
             .eq('id', id)
             .select()
             .single();

         console.log('updateBorrower response:', response);
         return response;
     } catch (error: any) {
         console.error('Unexpected error in updateBorrower:', error);
         const pgError: PostgrestError = {
             message: error?.message || 'Client Update Error',
             details: error?.details || '',
             hint: error?.hint || '',
             code: error?.code || 'CLIENT_UPDATE_ERROR',
             name: 'ClientSideUpdateError'
         };
         return { data: null, error: pgError, status: 0, statusText: 'Client Update Error', count: null };
     }
  }

  async deleteBorrower(id: number): Promise<PostgrestSingleResponse<null>> {
    this.isLoading.set(true);
    try {
      const response = await this.supabase
        .from(this.tableName)
        .delete()
        .match({ id });

      if (response.error) {
        console.error('Supabase delete error:', response.error);
        // Ensure a PostgrestError structure is returned even on unexpected client errors
        const pgError: PostgrestError = {
            message: response.error.message || 'Client Delete Error',
            details: response.error.details || '',
            hint: response.error.hint || '',
            code: response.error.code || 'CLIENT_DELETE_ERROR',
            name: 'ClientSideDeleteError'
        };
         return { data: null, error: pgError, status: response.status, statusText: response.statusText, count: response.count };
      }

      // Successfully deleted, data is typically null for delete
      console.log('Successfully deleted borrower with id:', id);
      return { data: null, error: null, status: response.status, statusText: response.statusText, count: response.count };

    } catch (error: any) {
        console.error('Unexpected error in deleteBorrower:', error);
        const pgError: PostgrestError = {
            message: error?.message || 'Unexpected Client Delete Error',
            details: error?.details || '',
            hint: error?.hint || '',
            code: error?.code || 'UNEXPECTED_DELETE_ERROR',
            name: 'UnexpectedClientDeleteError'
        };
        return { data: null, error: pgError, status: 0, statusText: 'Unexpected Client Error', count: null };
    } finally {
        this.isLoading.set(false);
    }
  }

  /**
   * Fetches all loans associated with a specific borrower ID.
   * @param borrowerId The ID of the borrower whose loans to fetch.
   * @returns Promise resolving to the Supabase response containing an array of Loans or an error.
   */
  async getLoansByBorrowerId(borrowerId: number): Promise<PostgrestSingleResponse<Loan[]>> {
    this.isLoading.set(true);
    try {
      const response = await this.supabase
        .from('loans') // Assuming your loans table is named 'loans'
        .select('*')
        .eq('account_id', borrowerId) // Assuming the foreign key column is 'borrower_id'
        .order('created_at', { ascending: false });

        console.log(`getLoansByBorrowerId (${borrowerId}) response:`, response);
        return response;

    } catch (error: any) {
        console.error(`Unexpected error fetching loans for borrower ${borrowerId}:`, error);
        const pgError: PostgrestError = {
            message: error?.message || 'Unexpected Client Loan Fetch Error',
            details: error?.details || '',
            hint: error?.hint || '',
            code: error?.code || 'UNEXPECTED_LOAN_FETCH_ERROR',
            name: 'UnexpectedClientLoanFetchError'
        };
        return { data: null, error: pgError, status: 0, statusText: 'Unexpected Client Error', count: null };
    } finally {
        this.isLoading.set(false);
    }
  }

  // Add methods for filtering, pagination, adding, updating, deleting borrowers later
}
